### ISSUE TITLE
Empty package

### ISSUE THREAD

**Issue by ftomassetti** [openvalidation/openvalidation#65]
If I run:
```
java -jar openvalidation.jar --culture en --language java \
     --rule "your age HAS to be greater than 22" --schema "{ age: 21 }" --output age_check.js
```
This file is generated:
```
package ;




public class HUMLValidator implements HUMLFramework.IOpenValidator
{
    public HUMLFramework huml;

    public HUMLValidator()
    {
        huml = new HUMLFramework();



        huml.appendRule("",
           new String[]{ "age" },
           "your age HAS to be greater than 22",
           ( model) -> huml.LESS_OR_EQUALS(model.getAge(), 22.0),
           false
        );



    }

    public String getValidatorID(){
        return "";
    }

    public HUMLFramework.OpenValidationSummary validate( model) {
        return huml.validate(model);
    }

    @Override
    public HUMLFramework.OpenValidationSummary validate(Object model) {
        return this.validate(()model);
    }


}
```

Not the first line where the keyword package is followed by a semicolon

**Comment by thecodemonkey** [comment]
You're right. A default package is missing. We could just generate **io.openvalidation.rules** as the default package. 

Otherwise, if you need a custom package name, you can parameterize with:

    -p model_type=org.package.Data;generated_class_namespace=org.package.rules;generated_class_name=MyValidator

I have just seen that it is not yet properly [documented](https://docs.openvalidation.io/openvalidation-cli). There is still a lot to be done. I think I'll get to work. I am on holiday and now I have time for that ;-)

**Comment by thecodemonkey** [comment]
I have just completed the documentation: 
https://docs.openvalidation.io/openvalidation-cli#params

![image](https://user-images.githubusercontent.com/1646017/71245871-efa3db80-2315-11ea-89ad-c3bcb94d88f4.png)

**Comment by thecodemonkey** [comment]
done.
